# Generated by Django 2.2.7 on 2019-11-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0018_auto_20191118_2253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Season',
        ),
    ]
